name: CalSync
options:
  bundleIdPrefix: com.appschmiede
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual

targets:
  CalSync:
    type: application
    platform: macOS
    sources:
      - path: CalSync
        excludes:
          - "**/*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.appschmiede.CalSync
        INFOPLIST_FILE: CalSync/Info.plist
        CODE_SIGN_ENTITLEMENTS: CalSync/CalSync.entitlements
        ENABLE_HARDENED_RUNTIME: false
        PRODUCT_NAME: CalSync
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: true
    entitlements:
      path: CalSync/CalSync.entitlements
